site_name: clsproperties
site_url: https://icb08.github.io/clsproperties/
repo_name: clsproperties
repo_url: https://github.com/icb08/clsproperties

nav:
  - Home: index.md
  - Getting Started: documentation.md
  - Guides:
    - Installation: guides/installation.md
    - Importation: guides/importation.md
    - Implementation using Decorators: guides/implementation-decorator.md
    - Implementation using Callables: guides/implementation-callable.md
  - Examples:
    - Basic Example (Decorator): examples/decorator.md
    - Advanced Example (Callable): examples/callable.md
  - Reference:
    - Classes: reference/classes.md

theme: 
  name: material
  icon:
    logo: fontawesome/solid/book
    repo: octicons/mark-github-16
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Light Mode


plugins:
  - search
  - mike
  - gh-admonitions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown_include.include:
      base_path: .

extra:
  version:
    provider: mike

extra_css: 
  - stylesheets/extra.css